name: Build Installers

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            requirements_tf: requirements_tf.txt
            architecture: windows-x64
          - os: macos-latest
            requirements_tf: requirements_tf_mac.txt
            architecture: macos-arm64

    steps:
    - name: Checkout repo
      uses: actions/checkout@v6

    - name: Write release version
      shell: bash
      run: |
        VERSION="${GITHUB_REF_NAME#v}"
        echo "VERSION=$VERSION" >> "$GITHUB_ENV"

    - name: Extract InstallForge (Windows)
      if: startsWith(matrix.os, 'windows-')
      run: |
        Expand-Archive -Path app\tools\InstallForge.zip -DestinationPath app\tools

    - name: Install create-dmg (macOS)
      if: startsWith(matrix.os, 'macos-')
      run: |
        brew install create-dmg

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ..
        pip install -r requirements.txt
        pip install -r ${{ matrix.requirements_tf }}
        pip install pyinstaller
      working-directory: ./app

    - name: Set correct version numbers
      shell: bash
      run: |
        python replace_version.py "${VERSION}" "${{ matrix.architecture }}"
      working-directory: ./app

    - name: Build executable with PyInstaller
      run: |
        pyinstaller app.spec --noconfirm
      working-directory: ./app

    - name: Build Windows installer with InstallForge
      if: startsWith(matrix.os, 'windows-')
      run: |
        .\ifbuildx86.exe -i ..\..\..\app.ifp
      working-directory: ./app/tools/InstallForge/bin

    - name: Build macOS Disk Image with create-dmg
      if: startsWith(matrix.os, 'macos-')
      run: |
        ./build_dmg.sh
      working-directory: ./app

    - name: Upload installer (Windows)
      if: startsWith(matrix.os, 'windows-')
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.architecture }}-installer
        path: .\app\dist\sirkku-*-setup.exe

    - name: Upload installer (macOS)
      if: startsWith(matrix.os, 'macos-')
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.architecture }}-installer
        path: ./app/dist/sirkku-*.dmg
