name: Build Windows Installer

on:
  push:
    branches: [ desktop-app ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v6

    - name: Remove placeholder models folder
      run: Remove-Item -Recurse -Force models

    - name: Get models from private repo
      uses: actions/checkout@v6
      with:
        repository: luomus/bird-identification-models
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        path: models

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ..
        pip install -r requirements.txt
        pip install pyinstaller
      working-directory: ./app

    - name: Build executable with PyInstaller
      run: |
        pyinstaller app.spec --noconfirm
      working-directory: ./app

    - name: Download InstallForge
      run: |
        curl -L -o installforge.exe "https://github.com/soner-boztas/installforge/releases/download/v1.5.0/IFInst.exe"

    - name: Install InstallForge silently
      run: |
        .\installforge.exe /S

    - name: Build installer with InstallForge
      run: |
        & "C:\Program Files (x86)\solicus\InstallForge\bin\ifbuildx86.exe" -i app.ifp
      working-directory: ./app

    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Installer
        path: .\app\dist\birdIdentifier.exe
